apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy-to-gke
on:
  push:
    branches:
      - "**"
jobs:
  gcloud:
    env:
      deploy: "false"
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Create credential file from secret
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy == 'true'}}
        name: Google Cloud authentication and HELM deployment
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install mysql-mlcb bitnami/mysql
          helm list
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy != 'true'}}
        name: Google Cloud authentication and undeployment
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap002 --region us-east1 --project mlcbplatformproject 
          helm uninstall mysql-mlcb