apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy-to-gke
on:
  push:
    branches:
      - "**"
jobs:
  gcloud:
    env:
      deploy: "true"
    steps:
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        name: Create credential file from secret
        run: |
          rm -rf ${HOME}/.kube
          mkdir ${HOME}/.kube && cat >> ${HOME}/.kube/config.json << EOF
          ${{ secrets.mlcbMultilinePass }}
          EOF
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy == 'true'}}
        name: Google Cloud authentication and deployment
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject 
          helm -h
      - uses: docker://kiwigrid/gcloud-kubectl-helm:latest
        if: ${{ env.deploy != 'true'}}
        name: Google Cloud authentication and undeployment
        run: |
          gcloud auth login --cred-file=${HOME}/.kube/config.json 
          gcloud config set project mlcbplatformproject
          gcloud container clusters get-credentials mlcb-platform-cluster-ap001 --region us-east1 --project mlcbplatformproject 
          kubectl delete service deployment-mlcb
          kubectl delete deployment deployment-mlcb
